language: objective-c
osx_image: xcode8
rvm:
- 2.1.2
sudo: true
before_install:
- gem install shenzhen
- chmod a+x ./Scripts/install.sh
install:
- "./Scripts/install.sh"
before_script:
- chmod a+x ./Scripts/build.sh
script:
- "./Scripts/build.sh"
